# DHT22 temperature and humidity sensor
DHT22_PIN_NUM = 22
DHT22_SAMPLING_INTERVAL = 2
MAX_SENSOR_FAILS = 10

# LEDs
ONBOARD_LED_PIN_NUM = 25
ATTACHED_LED_PIN_NUM = 13
LED_BLINK_INTERVAL = 250

# Temperature control parameters
TARGET_TEMPERATURE = 25.0
TEMPERATURE_DEVIATION_TOLERANCE = 0.5
TEMPERATURE_MAX_TOLERANCE = 2.0

# Heater relay
HEATER_RELAY_PIN_NUM = 16
HEATER_RELAY_ACTIVE_LOW = False
